[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyPPG"
version = "1.0.73"
description = "pyPPG: a python toolbox for PPG morphological analysis."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"

authors = [
    { name = "Marton A. Goda, PhD", email = "marton.goda@campus.technion.ac.il" },
    { name = "Peter H. Charlton, PhD" }
]

license = { text = "AGPL-3.0-or-later" }

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent"
]

dependencies = [
    "scipy>=1.9.1",
    "numpy>=1.23.2",
    "dotmap==1.3.30",
    "pandas>=1.4.4",
    "wfdb==3.4.0",
    "mne==1.5.0",
    "Eel==0.14.0",
    "Jinja2==3.1.2",
    "MarkupSafe==2.1.1",
    "Pillow==9.2.0",
    "altgraph==0.17.3",
    "appdirs==1.4.4",
    "attrs==22.1.0",
    "auto-py-to-exe==2.23.1",
    "boltons==21.0.0",
    "bottle==0.12.23",
    "bottle-websocket==0.2.9",
    "certifi==2022.9.24",
    "cffi==1.15.1",
    "chardet==5.0.0",
    "charset-normalizer==2.1.1",
    "colorama==0.4.5",
    "contourpy==1.0.5",
    "cycler==0.11.0",
    "decorator==5.1.1",
    "dotteddict==2016.3.11",
    "face==20.1.1",
    "fonttools==4.37.1",
    "future==0.18.2",
    "gevent==21.12.0",
    "gevent-websocket==0.10.1",
    "glom==22.1.0",
    "greenlet==1.1.3",
    "heartpy==1.2.7",
    "idna==3.4",
    "joblib>=1.2.0",
    "kiwisolver==1.4.4",
    "matplotlib>=3.6.1",
    "mpldatacursor==0.7.1",
    "packaging==21.3",
    "parallel-map==0.2.1",
    "patsy==0.5.3",
    "pefile==2022.5.30",
    "pip>=21.3.1",
    "pooch==1.6.0",
    "pycparser==2.21",
    "pyinstaller==5.5",
    "pyinstaller-hooks-contrib==2022.10",
    "pyparsing==3.0.9",
    "python-dateutil==2.8.2",
    "pytz==2022.4",
    "pywin32-ctypes==0.2.0",
    "requests==2.28.1",
    "scikit-learn>=1.1.3",
    "scipy>=1.9.1",
    "setuptools==60.2.0",
    "six==1.16.0",
    "sphinx-rtd-theme==1.3.0",
    "soundfile==0.11.0",
    "statsmodels>=0.13.2",
    "threadpoolctl==3.1.0",
    "tqdm>=4.64.1",
    "urllib3==1.26.12",
    "wheel==0.37.1",
    "whichcraft==0.6.1",
    "zope.event==4.5.0",
    "zope.interface==5.4.0",
]

[project.urls]
Homepage = "https://github.com/godamartonaron/GODA_pyPPG"
BugTracker = "https://github.com/pypa/sampleproject/issues"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["pyPPG", "pyPPG.ppg_bm", "pyPPG.pack_ppg", "pyPPG.validation"]

[tool.setuptools.package-data]
pyPPG = ["*"]
"pyPPG.ppg_bm" = ["*"]
"pyPPG.pack_ppg" = ["*"]
"pyPPG.validation" = ["pw_anal.py", "__init__.py"]